# This is the serverless.yml file for deploying an AWS Lambda function
# and API Gateway that can generate PDFs from Pug templates

service: pdf-generator

provider:
  name: aws
  region: eu-west-1
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      pdf_generator:
        path: ./

# This is the AWS Lambda function that will be deployed
functions:
  generate_pdf:
    image:
      name: pdf_generator
    timeout: 900
    memorySize: 2048